# Generated by Django 3.0.5 on 2021-05-29 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('nome_lugar', models.CharField(max_length=200)),
                ('tipo_lugar', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('quantidade_pessoas', models.IntegerField()),
                ('data_hora_ocorrido', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
