# Generated by Django 3.0.5 on 2021-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncias',
            name='data_hora_ocorrido',
        ),
        migrations.AddField(
            model_name='denuncias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
